version: '3'

services:
    db-postres-dev:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
        volumes:
            - /home/mycomputer/desenvolvimento/docker-Compose/postgresql:/var/lib/postgresql/data